// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.6.1.0
//      SpecFlow Generator Version:1.6.0.0
//      Runtime Version:4.0.30319.235
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace LetMeRate.Web.Acceptance.Specs.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.6.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Account validation")]
    public partial class AccountValidationFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "VerifyAccount.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Account validation", "In order to validate my account\r\nAs a user of rating\r\nI want to be sent a validat" +
                    "ion link", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Validating account that is valid")]
        [NUnit.Framework.CategoryAttribute("CreateUserAccounts")]
        [NUnit.Framework.CategoryAttribute("ClearDatabase")]
        public virtual void ValidatingAccountThatIsValid()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validating account that is valid", new string[] {
                        "CreateUserAccounts",
                        "ClearDatabase"});
#line 8
this.ScenarioSetup(scenarioInfo);
#line 9
 testRunner.Given("I am making web request");
#line 10
 testRunner.When("sending my validation key");
#line 11
 testRunner.Then("I should see a result that I am validated");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Validating account that\'s not valid")]
        [NUnit.Framework.CategoryAttribute("CreateUserAccounts")]
        [NUnit.Framework.CategoryAttribute("ClearDatabase")]
        public virtual void ValidatingAccountThatSNotValid()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validating account that\'s not valid", new string[] {
                        "CreateUserAccounts",
                        "ClearDatabase"});
#line 16
this.ScenarioSetup(scenarioInfo);
#line 17
testRunner.Given("I am making web request");
#line 18
testRunner.When("sending my validation key that is invalid");
#line 19
testRunner.Then("I should see a result that I am not validated");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
